<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <RootNamespace>MgsvModBldr.Tools.Pftxs</RootNamespace>
    <AssemblyName>MgsvModBldr.Tools.Pftxs</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MgsvModBldr.Tools.GameHashing\MgsvModBldr.Tools.GameHashing.csproj" />
    <ProjectReference Include="..\MgsvModBldr.Tools.Qar\MgsvModBldr.Tools.Qar.csproj" />
  </ItemGroup>
</Project>
