<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>MgsvModBldr.Tools.Sbp.Tests</RootNamespace>
    <AssemblyName>MgsvModBldr.Tools.Sbp.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MgsvModBldr.Tools.Sbp\MgsvModBldr.Tools.Sbp.csproj" />
    <ProjectReference Include="..\MgsvModBldr.Tools.Testing\MgsvModBldr.Tools.Testing.csproj" />
  </ItemGroup>
</Project>
